version: '3'

services:
  base: &base
    hostname: base
    image: paullx/analysis-system
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app

  app: &app
    <<: *base
    hostname: app
    command: npm run dev
    ports:
      - "3000:80"